# deploy.yml 최종 확인용 (수정 불필요)
name: Deploy to EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            git config --global --add safe.directory /jinro/docker-project/backend
            git config --global --add safe.directory /jinro/docker-project/frontend
            
            cd /jinro/docker-project/backend
            
            git fetch origin
            git reset --hard origin/master
            
            cd /jinro/docker-project
            
            sudo docker-compose down
            sudo docker-compose up -d --build
            sudo docker system prune -af
